//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArchitecturePro.DataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CamilaMoraes : DbContext
    {
        public CamilaMoraes()
            : base("name=CamilaMoraes")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tb_acessos> tb_acessos { get; set; }
        public virtual DbSet<tb_cliente> tb_cliente { get; set; }
        public virtual DbSet<tb_despesas> tb_despesas { get; set; }
        public virtual DbSet<tb_empresa> tb_empresa { get; set; }
        public virtual DbSet<tb_fases> tb_fases { get; set; }
        public virtual DbSet<tb_fasesProjeto> tb_fasesProjeto { get; set; }
        public virtual DbSet<tb_fluxoCaixa> tb_fluxoCaixa { get; set; }
        public virtual DbSet<tb_grupoFinanceiro> tb_grupoFinanceiro { get; set; }
        public virtual DbSet<tb_ItemPedido> tb_ItemPedido { get; set; }
        public virtual DbSet<tb_orcamento> tb_orcamento { get; set; }
        public virtual DbSet<tb_projeto> tb_projeto { get; set; }
        public virtual DbSet<tb_projetoFluxoCaixa> tb_projetoFluxoCaixa { get; set; }
        public virtual DbSet<tb_servicos> tb_servicos { get; set; }
        public virtual DbSet<tb_telas> tb_telas { get; set; }
        public virtual DbSet<tb_unidade> tb_unidade { get; set; }
        public virtual DbSet<tb_usuario> tb_usuario { get; set; }
        public virtual DbSet<tb_mensagens> tb_mensagens { get; set; }
    }
}
