//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArchitecturePro.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_acessos
    {
        public long ace_Id { get; set; }
        public long ace_UsrId { get; set; }
        public long ace_TelasId { get; set; }
    
        public virtual tb_telas tb_telas { get; set; }
        public virtual tb_usuario tb_usuario { get; set; }
    }
}
