//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArchitecturePro.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_cliente()
        {
            this.tb_projeto = new HashSet<tb_projeto>();
        }
    
        public long cli_Id { get; set; }
        public string cli_Descricao { get; set; }
        public string cli_Fantasia { get; set; }
        public string cli_CpfCnpj { get; set; }
        public string cli_Logradouro { get; set; }
        public string cli_Numero { get; set; }
        public string cli_Cidade { get; set; }
        public string cli_Estado { get; set; }
        public string cli_CEP { get; set; }
        public string cli_Complemento { get; set; }
        public string cli_Contato { get; set; }
        public string cli_Telefone { get; set; }
        public string cli_Celular { get; set; }
        public string cli_Email { get; set; }
        public System.DateTime cli_Data { get; set; }
        public bool cli_Ativo { get; set; }
        public string cli_Bairro { get; set; }
        public string cli_LogradouroObra { get; set; }
        public string cli_NumeroObra { get; set; }
        public string cli_CidadeObra { get; set; }
        public string cli_EstadoObra { get; set; }
        public string cli_CEPObra { get; set; }
        public string cli_ComplementoObra { get; set; }
        public string cli_BairroObra { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_projeto> tb_projeto { get; set; }
    }
}
