//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArchitecturePro.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_despesas
    {
        public long des_Id { get; set; }
        public string des_Descricao { get; set; }
        public long des_GrfId { get; set; }
    
        public virtual tb_grupoFinanceiro tb_grupoFinanceiro { get; set; }
    }
}
