//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArchitecturePro.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_empresa
    {
        public long emp_Id { get; set; }
        public string emp_Nome { get; set; }
        public string emp_CNPJ { get; set; }
        public string emp_Telefone { get; set; }
        public string emp_Logradouro { get; set; }
        public string emp_Numero { get; set; }
        public string emp_Bairro { get; set; }
        public string emp_Cidade { get; set; }
        public string emp_Estado { get; set; }
        public string emp_Complemento { get; set; }
        public string emp_CEP { get; set; }
        public string emp_RazaoSocial { get; set; }
        public string emp_VersaoSistema { get; set; }
        public string emp_LocalVersao { get; set; }
        public string emp_Email { get; set; }
        public string emp_LoginPagSeguro { get; set; }
        public string emp_TokenPagSeguro { get; set; }
        public string emp_TestePagSeguro { get; set; }
        public string emp_SenhaEmail { get; set; }
    }
}
