//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArchitecturePro.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_fluxoCaixa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_fluxoCaixa()
        {
            this.tb_projetoFluxoCaixa = new HashSet<tb_projetoFluxoCaixa>();
        }
    
        public long flc_Id { get; set; }
        public System.DateTime flc_DataCadastro { get; set; }
        public bool flc_Entrada { get; set; }
        public long flc_UsrId { get; set; }
        public string flc_Descricao { get; set; }
        public decimal flc_Valor { get; set; }
        public System.DateTime flc_DataCaixa { get; set; }
        public Nullable<long> flc_GrfId { get; set; }
        public byte flc_PagSeguro { get; set; }
        public byte flc_PagamentoConfirmado { get; set; }
        public string flc_URLPagamento { get; set; }
    
        public virtual tb_usuario tb_usuario { get; set; }
        public virtual tb_grupoFinanceiro tb_grupoFinanceiro { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_projetoFluxoCaixa> tb_projetoFluxoCaixa { get; set; }
    }
}
