//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArchitecturePro.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_grupoFinanceiro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_grupoFinanceiro()
        {
            this.tb_despesas = new HashSet<tb_despesas>();
            this.tb_fluxoCaixa = new HashSet<tb_fluxoCaixa>();
        }
    
        public long grf_Id { get; set; }
        public string grf_Descricao { get; set; }
        public bool grf_Ativo { get; set; }
        public System.DateTime grf_Data { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_despesas> tb_despesas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_fluxoCaixa> tb_fluxoCaixa { get; set; }
    }
}
