//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArchitecturePro.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ItemPedido
    {
        public long ipo_Id { get; set; }
        public long ipo_SerId { get; set; }
        public long ipo_Qtde { get; set; }
        public decimal ipo_Valor { get; set; }
        public long ipo_PrjId { get; set; }
    
        public virtual tb_projeto tb_projeto { get; set; }
        public virtual tb_servicos tb_servicos { get; set; }
    }
}
