//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArchitecturePro.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_mensagens
    {
        public long msg_Id { get; set; }
        public string msg_Texto { get; set; }
        public System.DateTime msg_DataHora { get; set; }
        public byte msg_Lida { get; set; }
        public long msg_UsrId { get; set; }
        public long msg_UsrIdEnvio { get; set; }
    
        public virtual tb_usuario tb_usuario { get; set; }
    }
}
