//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArchitecturePro.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_projeto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_projeto()
        {
            this.tb_fasesProjeto = new HashSet<tb_fasesProjeto>();
            this.tb_ItemPedido = new HashSet<tb_ItemPedido>();
            this.tb_orcamento = new HashSet<tb_orcamento>();
            this.tb_projetoFluxoCaixa = new HashSet<tb_projetoFluxoCaixa>();
        }
    
        public long prj_Id { get; set; }
        public long prj_CliId { get; set; }
        public System.DateTime prj_DataInicio { get; set; }
        public System.DateTime prj_DataFimPrevista { get; set; }
        public System.DateTime prj_DataFimReal { get; set; }
        public long prj_UsrId { get; set; }
        public string prj_Obs { get; set; }
        public long prj_PerGanho { get; set; }
        public decimal prj_Arredondamento { get; set; }
    
        public virtual tb_cliente tb_cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_fasesProjeto> tb_fasesProjeto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_ItemPedido> tb_ItemPedido { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_orcamento> tb_orcamento { get; set; }
        public virtual tb_usuario tb_usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_projetoFluxoCaixa> tb_projetoFluxoCaixa { get; set; }
    }
}
