//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArchitecturePro.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_telas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_telas()
        {
            this.tb_acessos = new HashSet<tb_acessos>();
        }
    
        public long tel_Id { get; set; }
        public string tel_Nome { get; set; }
        public string tel_frmPrincipal { get; set; }
        public string tel_Icone { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_acessos> tb_acessos { get; set; }
    }
}
